name: cd

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v6

            - name: Set up Node
              uses: actions/setup-node@v5
              with:
                node-version: 25

            - name: install dependencies
              run: npm ci

            - name: build the code
              run: npm run build